export const JOB_TITLES: string[] = [
  "Student",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Data Analyst",
  "Business Analyst",
  "System Analyst",
  "Project Manager",
  "Product Manager",
  "QA Engineer",
  "DevOps Engineer",
  "Cyber Security Analyst",
  "Cloud Engineer",
  "Network Engineer",
  "Database Administrator",
  "Machine Learning Engineer",
  "AI Engineer",
  "HR Specialist",
  "Recruiter",
  "Marketing Specialist",
  "Digital Marketer",
  "Sales Representative",
  "Customer Support",
  "Teacher",
  "Accountant",
  "Financial Analyst",
  "Lawyer",
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Architect",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Content Creator",
  "Social Media Manager",
  "Photographer",
  "Video Editor",
  "Translator",
  "Administrative Assistant",
  "Operations Manager",
  "Other",
];

export const EXPERIENCE_OPTIONS: string[] = [
  "No experience",
  "Less than 1 year",
  "1 year",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6 years",
  "7 years",
  "8 years",
  "9 years",
  "10+ years",
];

export const ALL_SKILLS: string[] = [
  "Communication",
  "Teamwork",
  "Leadership",
  "Problem Solving",
  "Critical Thinking",
  "Time Management",
  "Creativity",
  "Adaptability",
  "Presentation Skills",
  "Negotiation",
  "Sales",
  "Customer Service",
  "Project Management",
  "Marketing",
  "Digital Marketing",
  "SEO",
  "Content Writing",
  "Copywriting",
  "Social Media",
  "Branding",
  "Recruitment",
  "HR Management",
  "Accounting",
  "Bookkeeping",
  "Financial Analysis",
  "Excel",
  "Word",
  "PowerPoint",
  "Data Entry",
  "Research",
  "Teaching",
  "Training",
  "Coaching",
  "Public Speaking",
  "Translation",
  "Arabic",
  "Hebrew",
  "English",
  "French",
  "German",
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "C",
  "C++",
  "C#",
  "PHP",
  "Kotlin",
  "Swift",
  "Go",
  "Rust",
  "SQL",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue",
  "Node.js",
  "Express.js",
  "Spring Boot",
  "Django",
  "Flask",
  "Laravel",
  "REST APIs",
  "GraphQL",
  "Git",
  "GitHub",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Linux",
  "Networking",
  "Cybersecurity",
  "Penetration Testing",
  "Machine Learning",
  "Deep Learning",
  "Data Analysis",
  "Data Visualization",
  "Power BI",
  "Tableau",
  "Figma",
  "Adobe Photoshop",
  "Illustrator",
  "Video Editing",
  "Photography",
  "AutoCAD",
  "SAP",
  "CRM",
  "ERP",
];
