export const ISRAELI_CITIES: string[] = [
  "Tel Aviv-Yafo",
  "Jerusalem",
  "Haifa",
  "Rishon LeZion",
  "Petah Tikva",
  "Ashdod",
  "Netanya",
  "Beer Sheva",
  "Bnei Brak",
  "Holon",
  "Ramat Gan",
  "Bat Yam",
  "Rehovot",
  "Ashkelon",
  "Herzliya",
  "Kfar Saba",
  "Hadera",
  "Modiin-Maccabim-Reut",
  "Nazareth",
  "Raanana",
  "Nahariya",
  "Kiryat Gat",
  "Eilat",
  "Tiberias",
  "Safed",
  "Beit Shemesh",
  "Ramla",
  "Lod",
  "Karmiel",
  "Yavne",
  "Hod HaSharon",
  "Givatayim",
  "Kiryat Ata",
  "Kiryat Motzkin",
  "Kiryat Bialik",
  "Kiryat Yam",
  "Nof HaGalil",
  "Or Yehuda",
  "Ramat HaSharon",
  "Rosh HaAyin",
  "Afula",
  "Dimona",
  "Migdal HaEmek",
  "Tirat Carmel",
  "Sderot",
  "Netivot",
  "Ofakim",
  "Arad",
  "Yokneam Illit",
  "Zichron Yaakov",
  "Binyamina",
  "Caesarea",
  "Even Yehuda",
  "Kfar Yona",
  "Pardes Hanna-Karkur",
  "Gan Yavne",
  "Nes Ziona",
  "Beer Yaakov",
  "Ganei Tikva",
  "Kiryat Ono",
  "Yehud-Monosson",
  "Rosh Pina",
  "Kiryat Shmona",
  "Maalot-Tarshiha",
  "Acre",
  "Umm al-Fahm",
  "Tayibe",
  "Tira",
  "Baqa al-Gharbiyye",
  "Sakhnin",
  "Shfaram",
  "Daliyat al-Karmel",
  "Beit Shean",
  "Yeruham",
  "Mitzpe Ramon",
  "Kfar Qasim",
  "Nazareth Illit",
  "Or Akiva",
  "Beitar Illit",
  "Modiin Illit",
  "Elad",
  "Tzur Hadassah",
  "Mevaseret Zion",
  "Kiryat Malachi",
  "Kiryat Ekron",
  "Kiryat Tivon",
  "Nesher",
  "Tirat Yehuda",
  "Shoham",
  "Gedera",
  "Kadima-Zoran",
  "Tzfat",
  "Kfar Vradim",
  "Maale Adumim",
  "Ariel",
  "Efrat",
  "Katzrin",
  "Bet Dagan",
  "Azor",
  "Rishpon",
  "Ganei Tal",
  "Mazkeret Batya",
  "Gan Yoshiya",
  "Kfar Shmaryahu",
  "Savyon",
  "Omer",
  "Lehavim",
  "Meitar",
  "Rahat",
  "Segev Shalom",
  "Hura",
  "Tel Sheva",
  "Fureidis",
  "Jisr az-Zarqa",
  "Ein Mahil",
  "Reineh",
  "Kafr Kanna",
  "Iksal",
  "Deir al-Asad",
  "Julis",
  "Peki'in",
  "Beit Jann",
  "Yirka",
];
